server token handle
FACN8/Donator-server pull request #7
Opened 2020-03-16 16:07 UTC by FrancisA2000

2020-03-16 16:31 UTC, Karyum requested changes
remove all the `JSON.stringify` when you do `res.send` it's pointless since express does it for you

2020-03-16 16:31 UTC, Karyum commented on src/middlewares/authCheck.js
> +    const newToken = token.slice(7,token.length)
if `authorization` header doesn't exist, it looks like your server will crash

2020-03-16 16:31 UTC, Karyum commented on src/middlewares/authCheck.js
> +    const newToken = token.slice(7,token.length)
also slicing the token is weird im guessing it's something to do with `ZoIiwiY`?

2020-03-16 16:32 UTC, Karyum commented
@FrancisA2000 again issue and description for this PR

2020-03-17 09:03 UTC, Karyum commented
@FrancisA2000 assign me when this branch is ready

2020-03-17 09:07 UTC, Karyum commented
@FrancisA2000 issue and description, you know next projects are client projects, right now with these PRs im being very nice but i can't promise the same behavior next projects.

2020-03-17 09:17 UTC, FrancisA2000 commented
In this PR it changes the way we handle the token and send it as an object to the front-end instead of putting it in the cookies, In this feature, it allow the front-end to set it as a cookie, and every time we send a request to the server it will look for the token in the headers to know witch user is sending the request, in addition tit will secure the website.

2020-03-17 09:47 UTC, Karyum commented
@FrancisA2000 i made an issue and modified the pull request description, is it correct or do i need to change something ? i hope this helps you open issues in the future before working on a task and making a PR

2020-03-17 09:53 UTC, FrancisA2000 commented
aa ok cool,
thanks,

2020-03-17 12:03 UTC, Karyum approved these changes
looks great

2020-03-17 12:03 UTC, merged